stages:
  - build-assets
  - check-style27
  - check-style
  - lint27
  - lint
  - doctest
  - compile
  - run-test27
  - run-test

build:
  stage: build-assets
  image: node:7.10.1
  variables:
    NODE_ENV: production
  before_script:
    - npm install --global npm@5.5.1
    - node --version
    - npm --version
    - npm install --ignore-scripts
  script:
    - node_modules/.bin/gulp
  cache:
    untracked: true
    paths:
      - node_modules
  except:
    - tags

check27:
  stage: check-style27
  image: python:2.7.13
  variables:
    ENV: development
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - make clean
    - make setup
  script:
    - make check
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

check:
  stage: check-style
  image: python:3.5.4
  variables:
    ENV: development
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - make clean
    - make setup
  script:
    - make check
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

lint27:
  stage: lint27
  image: python:2.7.13
  variables:
    PIP_CACHE_DIR: pip-cache
  before_script:
    - python --version
    - pip --version
    - ENV=development make setup
    - ENV=test make setup
  script:
    - make lint
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

lint:
  stage: lint
  image: python:3.5.4
  variables:
    PIP_CACHE_DIR: pip-cache
  before_script:
    - python --version
    - pip --version
    - ENV=development make setup
    - ENV=test make setup
  script:
    - make lint
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

doctest:
  stage: doctest
  image: python:2.7.13
  variables:
    PIP_CACHE_DIR: pip-cache
  before_script:
    - python --version
    - pip --version
    - ENV=development make setup
    - ENV=test make setup
  script:
    - make doctest
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

compile:
  stage: compile
  image: python:3.5.4
  variables:
    ENV: test
    APT_CACHE_DIR: apt-cache
    PIP_CACHE_DIR: pip-cache
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
      gcc zlib1g zlib1g-dev gettext
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - gettext --version
    - make clean
    - make setup
  script:
    - make catalog
  cache:
    untracked: true
    paths:
      - apt-cache
      - pip-cache
  artifacts:
    untracked: true
    paths:
      - locale
  except:
    - tags

test27:
  stage: run-test27
  image: python:2.7.13
  variables:
    ENV: test
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - make setup
  script:
    - make coverage
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

test:
  stage: run-test
  image: python:3.5.4
  variables:
    ENV: test
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - make setup
  script:
    - make coverage
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags
