stages:
  - build-assets
  - check-style
  - run-test

build:
  stage: build-assets
  image: node:7.8.0
  variables:
    NODE_ENV: production
  before_script:
    - node --version
    - npm --version
    - npm install
  script:
    - node_modules/.bin/gulp
  cache:
    untracked: true
    paths:
      - node_modules
  except:
    - tags

style:
  stage: check-style
  image: python:3.5
  variables:
    ENV: development
    PIP_CACHE_DIR: pip-cache
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
  script:
    - make setup
    - make check-style
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

test:
  stage: run-test
  image: python:3.5
  variables:
    ENV: test
    PIP_CACHE_DIR: pip-cache
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apt-get -qq update
    - apt-get -qq install -y --no-install-recommends gcc zlib1g zlib1g-dev
    - apt-get -qq install -y --no-install-recommends gettext
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - make setup
    - make catalog-compile
    - make clean
    - make coverage
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags
