stages:
  - vet
  - build
  - test
  - coverage

code-27:
  stage: vet
  image: python:2.7.14
  variables:
    ENV: development
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - make clean
    - make setup
  script:
    - make vet:code
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

code:
  stage: vet
  image: python:3.6.6
  variables:
    ENV: development
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - make clean
    - make setup
  script:
    - make vet:code
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

lint-27:
  stage: vet
  image: python:2.7.14
  variables:
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - ENV=development make setup
    - ENV=test make setup
  script:
    - make vet:lint
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

lint:
  stage: vet
  image: python:3.6.6
  variables:
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - ENV=development make setup
    - ENV=test make setup
  script:
    - make vet:lint
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

i18n:
  stage: build
  image: python:3.6.6
  variables:
    ENV: test
    APT_CACHE_DIR: apt-cache
    PIP_CACHE_DIR: pip-cache
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
      gcc zlib1g zlib1g-dev gettext
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - gettext --version
    - make setup
  script:
    - make i18n:compile
  cache:
    untracked: true
    paths:
      - apt-cache
      - pip-cache
  artifacts:
    untracked: true
    paths:
      - locale
  except:
    - tags

pack:
  stage: build
  image: node:8.11.4
  variables:
    NODE_ENV: production
  before_script:
    - node --version
    - npm --version
    - npm install --global gulp-cli
    - npm install --ignore-scripts
  script:
    - make pack
  cache:
    untracked: true
    paths:
      - node_modules
  artifacts:
    untracked: true
    paths:
      - static
  except:
    - tags

doctest27:
  stage: test
  image: python:2.7.14
  variables:
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - ENV=development make setup
    - ENV=test make setup
  script:
    - make test:doc
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

doctest:
  stage: test
  image: python:3.6.6
  variables:
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - ENV=development make setup
    - ENV=test make setup
  script:
    - make test:doc
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

test27:
  stage: test
  image: python:2.7.14
  variables:
    ENV: test
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - make setup
  script:
    - make test
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

test:
  stage: test
  image: python:3.6.6
  variables:
    ENV: test
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - make setup
  script:
    - make test
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

coverage:
  stage: coverage
  image: python:3.6.6
  variables:
    ENV: test
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - make setup
  script:
    - make test:coverage
  cache:
    untracked: true
    paths:
      - pip-cache
  artifacts:
    untracked: true
    paths:
      - .coverage
  except:
    - tags
